from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogtesttoolTTP(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 350)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 300, 241, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(130, 80, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 83, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(30, 183, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.comboBox2 = QtWidgets.QComboBox(Dialog)
        self.comboBox2.setGeometry(QtCore.QRect(130, 180, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.comboBox2.setFont(font)
        self.comboBox2.setObjectName("comboBox2")
        self.labelb = QtWidgets.QLabel(Dialog)
        self.labelb.setGeometry(QtCore.QRect(30, 53, 81, 16))
        self.labelb.setObjectName("labelb")
        self.comboBoxb = QtWidgets.QComboBox(Dialog)
        self.comboBoxb.setGeometry(QtCore.QRect(130, 50, 141, 22))
        self.comboBoxb.setFont(font)
        self.comboBoxb.setObjectName("comboBoxb")
        self.labelc = QtWidgets.QLabel(Dialog)
        self.labelc.setGeometry(QtCore.QRect(30, 113, 81, 16))
        self.labelc.setObjectName("labelc")
        self.comboBoxc = QtWidgets.QComboBox(Dialog)
        self.comboBoxc.setGeometry(QtCore.QRect(130, 110, 141, 22))
        self.comboBoxc.setFont(font)
        self.comboBoxc.setObjectName("comboBoxc")
        self.label2b = QtWidgets.QLabel(Dialog)
        self.label2b.setGeometry(QtCore.QRect(30, 213, 81, 16))
        self.label2b.setObjectName("label2b")
        self.comboBox2b = QtWidgets.QComboBox(Dialog)
        self.comboBox2b.setGeometry(QtCore.QRect(130, 210, 141, 22))
        self.comboBox2b.setFont(font)
        self.comboBox2b.setObjectName("comboBox2b")
        self.label3 = QtWidgets.QLabel(Dialog)
        self.label3.setGeometry(QtCore.QRect(30, 263, 81, 16))
        self.label3.setObjectName("label2b")
        self.lineedit = QtWidgets.QLineEdit(Dialog)
        self.lineedit.setGeometry(QtCore.QRect(130, 260, 141, 22))
        self.lineedit.setFont(font)
        self.lineedit.setObjectName("lineedit")

        self.labelintro = QtWidgets.QLabel(Dialog)
        self.labelintro.setGeometry(QtCore.QRect(30, 22, 121, 16))
        self.labelintro.setObjectName("labelintro")
        self.labelintro2 = QtWidgets.QLabel(Dialog)
        self.labelintro2.setGeometry(QtCore.QRect(30, 152, 121, 16))
        self.labelintro2.setObjectName("labelintro2")

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.accepted.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None))
        self.labelintro.setText(QtWidgets.QApplication.translate("Dialog", "Node Fields", None))
        self.labelintro2.setText(QtWidgets.QApplication.translate("Dialog", "Edge Fields", None))
        self.labelb.setText(QtWidgets.QApplication.translate("Dialog", "Node ID", None))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Field X", None))
        self.labelc.setText(QtWidgets.QApplication.translate("Dialog", "Field Y", None))
        self.label2.setText(QtWidgets.QApplication.translate("Dialog", "Start Field", None))
        self.label2b.setText(QtWidgets.QApplication.translate("Dialog", "End Field", None))
        self.label3.setText(QtWidgets.QApplication.translate("Dialog", "EPSG", None))

