from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogtesttoolGS(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 225)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(110, 175, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(110, 20, 101, 24))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 14, 91, 20))
        self.label.setObjectName("label")
        self.label.setFont(font)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 28, 91, 20))
        self.label_2.setObjectName("label_2")
        self.label_2.setFont(font)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(260, 14, 91, 20))
        self.label_3.setObjectName("label_3")
        self.label_3.setFont(font)
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(350, 20, 101, 24))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.setFont(font)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(260, 28, 91, 20))
        self.label_4.setObjectName("label_4")
        self.label_4.setFont(font)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 82, 111, 20))
        self.label_5.setObjectName("label_5")
        self.label_5.setFont(font)
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(140, 80, 51, 24))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.setFont(font)
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(120, 140, 101, 24))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.setFont(font)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 142, 86, 20))
        self.label_6.setObjectName("label_6")
        self.label_6.setFont(font)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.accepted.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Start nodes", None))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "field", None))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "End nodes", None))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "field", None))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Directed network ?", None))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Partition field", None))
