from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog3(object):
    def setupUi(self, Dialog3):
        Dialog3.setObjectName("Dialog3")
        Dialog3.resize(410, 280)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog3)
        self.buttonBox.setGeometry(QtCore.QRect(40, 230, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog3)
        self.label.setGeometry(QtCore.QRect(30, 20, 231, 20))
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog3)
        self.lineEdit.setGeometry(QtCore.QRect(340, 20, 41, 24))
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog3)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 50, 41, 24))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(Dialog3)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 301, 20))
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog3)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 281, 20))
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog3)
        self.lineEdit_3.setGeometry(QtCore.QRect(230, 110, 151, 24))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(Dialog3)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 201, 20))
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog3)
        self.label_5.setGeometry(QtCore.QRect(30, 140, 281, 20))
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(Dialog3)
        self.comboBox.setGeometry(QtCore.QRect(300, 140, 81, 24))
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label_6 = QtWidgets.QLabel(Dialog3)
        self.label_6.setGeometry(QtCore.QRect(30, 170, 91, 20))
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog3)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 170, 41, 24))
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(Dialog3)
        self.label_7.setGeometry(QtCore.QRect(230, 170, 91, 20))
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog3)
        self.lineEdit_5.setGeometry(QtCore.QRect(340, 170, 41, 24))
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog3)
        self.lineEdit_6.setGeometry(QtCore.QRect(230, 80, 151, 24))
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog3)
        self.lineEdit_7.setGeometry(QtCore.QRect(340, 200, 41, 24))
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_8 = QtWidgets.QLabel(Dialog3)
        self.label_8.setGeometry(QtCore.QRect(30, 200, 91, 20))
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(Dialog3)
        self.lineEdit_8.setGeometry(QtCore.QRect(140, 200, 41, 24))
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_9 = QtWidgets.QLabel(Dialog3)
        self.label_9.setGeometry(QtCore.QRect(230, 200, 91, 20))
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.directoryButton = QtWidgets.QPushButton("Choose", Dialog3)
        self.directoryButton.setGeometry(QtCore.QRect(150, 75, 61, 30))
        self.directoryButton.setFont(font)


        self.retranslateUi(Dialog3)
        self.buttonBox.rejected.connect(Dialog3.reject)
        self.buttonBox.accepted.connect(Dialog3.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog3)

    def retranslateUi(self, Dialog3):
        Dialog3.setWindowTitle(QtWidgets.QApplication.translate("Dialog3", "Dialog", None))
        self.label.setText(QtWidgets.QApplication.translate("Dialog3", "Number of iteration for random error", None))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog3", "Fraction of nodes removed (between 0 and 1)", None))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog3", "Save directory", None))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog3", "Image name", None))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog3", "File Format", None))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog3", "Image width", None))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog3", "Image height", None))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog3", "Stroke width", None))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog3", "Node width", None))
