# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui

class Ui_DialogtesttoolTTP(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 350)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        Dialog.setFont(font)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 300, 241, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(130, 80, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 83, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label2 = QtGui.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(30, 183, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.comboBox2 = QtGui.QComboBox(Dialog)
        self.comboBox2.setGeometry(QtCore.QRect(130, 180, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.comboBox2.setFont(font)
        self.comboBox2.setObjectName("comboBox2")
        self.labelb = QtGui.QLabel(Dialog)
        self.labelb.setGeometry(QtCore.QRect(30, 53, 81, 16))
        self.labelb.setObjectName("labelb")
        self.comboBoxb = QtGui.QComboBox(Dialog)
        self.comboBoxb.setGeometry(QtCore.QRect(130, 50, 141, 22))
        self.comboBoxb.setFont(font)
        self.comboBoxb.setObjectName("comboBoxb")
        self.labelc = QtGui.QLabel(Dialog)
        self.labelc.setGeometry(QtCore.QRect(30, 113, 81, 16))
        self.labelc.setObjectName("labelc")
        self.comboBoxc = QtGui.QComboBox(Dialog)
        self.comboBoxc.setGeometry(QtCore.QRect(130, 110, 141, 22))
        self.comboBoxc.setFont(font)
        self.comboBoxc.setObjectName("comboBoxc")
        self.label2b = QtGui.QLabel(Dialog)
        self.label2b.setGeometry(QtCore.QRect(30, 213, 81, 16))
        self.label2b.setObjectName("label2b")
        self.comboBox2b = QtGui.QComboBox(Dialog)
        self.comboBox2b.setGeometry(QtCore.QRect(130, 210, 141, 22))
        self.comboBox2b.setFont(font)
        self.comboBox2b.setObjectName("comboBox2b")
        self.label3 = QtGui.QLabel(Dialog)
        self.label3.setGeometry(QtCore.QRect(30, 263, 81, 16))
        self.label3.setObjectName("label2b")
        self.lineedit = QtGui.QLineEdit(Dialog)
        self.lineedit.setGeometry(QtCore.QRect(130, 260, 141, 22))
        self.lineedit.setFont(font)
        self.lineedit.setObjectName("lineedit")

        self.labelintro = QtGui.QLabel(Dialog)
        self.labelintro.setGeometry(QtCore.QRect(30, 22, 121, 16))
        self.labelintro.setObjectName("labelintro")
        self.labelintro2 = QtGui.QLabel(Dialog)
        self.labelintro2.setGeometry(QtCore.QRect(30, 152, 121, 16))
        self.labelintro2.setObjectName("labelintro2")


        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.labelintro.setText(QtGui.QApplication.translate("Dialog", "Node Fields", None, QtGui.QApplication.UnicodeUTF8))
        self.labelintro2.setText(QtGui.QApplication.translate("Dialog", "Edge Fields", None, QtGui.QApplication.UnicodeUTF8))
        self.labelb.setText(QtGui.QApplication.translate("Dialog", "Node ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Field X", None, QtGui.QApplication.UnicodeUTF8))
        self.labelc.setText(QtGui.QApplication.translate("Dialog", "Field Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label2.setText(QtGui.QApplication.translate("Dialog", "Start Field", None, QtGui.QApplication.UnicodeUTF8))
        self.label2b.setText(QtGui.QApplication.translate("Dialog", "End Field", None, QtGui.QApplication.UnicodeUTF8))
        self.label3.setText(QtGui.QApplication.translate("Dialog", "EPSG", None, QtGui.QApplication.UnicodeUTF8))

