# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui

class Ui_Dialog3(object):
    def setupUi(self, Dialog3):
        Dialog3.setObjectName("Dialog3")
        Dialog3.resize(400, 280)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog3)
        self.buttonBox.setGeometry(QtCore.QRect(30, 230, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtGui.QLabel(Dialog3)
        self.label.setGeometry(QtCore.QRect(30, 20, 231, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtGui.QLineEdit(Dialog3)
        self.lineEdit.setGeometry(QtCore.QRect(330, 20, 41, 20))
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtGui.QLineEdit(Dialog3)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 50, 41, 20))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtGui.QLabel(Dialog3)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 281, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(Dialog3)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 281, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtGui.QLineEdit(Dialog3)
        self.lineEdit_3.setGeometry(QtCore.QRect(220, 110, 151, 20))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtGui.QLabel(Dialog3)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 281, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(Dialog3)
        self.label_5.setGeometry(QtCore.QRect(30, 140, 281, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtGui.QComboBox(Dialog3)
        self.comboBox.setGeometry(QtCore.QRect(290, 140, 81, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_6 = QtGui.QLabel(Dialog3)
        self.label_6.setGeometry(QtCore.QRect(30, 170, 91, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtGui.QLineEdit(Dialog3)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 170, 41, 20))
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtGui.QLabel(Dialog3)
        self.label_7.setGeometry(QtCore.QRect(220, 170, 91, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtGui.QLineEdit(Dialog3)
        self.lineEdit_5.setGeometry(QtCore.QRect(330, 170, 41, 20))
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtGui.QLineEdit(Dialog3)
        self.lineEdit_6.setGeometry(QtCore.QRect(220, 80, 151, 20))
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtGui.QLineEdit(Dialog3)
        self.lineEdit_7.setGeometry(QtCore.QRect(330, 200, 41, 20))
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_8 = QtGui.QLabel(Dialog3)
        self.label_8.setGeometry(QtCore.QRect(30, 200, 91, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_8 = QtGui.QLineEdit(Dialog3)
        self.lineEdit_8.setGeometry(QtCore.QRect(140, 200, 41, 20))
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_9 = QtGui.QLabel(Dialog3)
        self.label_9.setGeometry(QtCore.QRect(220, 200, 91, 20))
        self.label_9.setObjectName("label_9")
        self.directoryButton = QtGui.QPushButton("Choose", Dialog3)
        self.directoryButton.setGeometry(QtCore.QRect(140, 75, 61, 30))
        

        self.retranslateUi(Dialog3)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog3.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog3.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog3)

    def retranslateUi(self, Dialog3):
        Dialog3.setWindowTitle(QtGui.QApplication.translate("Dialog3", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog3", "Number of iteration for random error", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog3", "Fraction of nodes removed (between 0 and 1)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog3", "Save directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog3", "Image name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog3", "File Format", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog3", "Image width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog3", "Image height", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog3", "Stroke width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog3", "Node width", None, QtGui.QApplication.UnicodeUTF8))

