# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui

class Ui_Dialogtesttooldraw(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(810, 340)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        Dialog.setFont(font)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(420, 290, 365, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        font = QtGui.QFont()
        font.setFamily("Calibri")

        self.bouton1 = QtGui.QPushButton("Change Color", Dialog)
        self.bouton1.setGeometry(QtCore.QRect(165, 40, 91, 22))
        self.label1 = QtGui.QLabel(Dialog)
        self.label1.setGeometry(QtCore.QRect(20, 43, 121, 16))
        self.label1.setObjectName("label1")
        self.lineedit = QtGui.QLineEdit(Dialog)
        self.lineedit.setGeometry(QtCore.QRect(105, 40, 22, 22))
        self.lineedit.setFont(font)
        self.lineedit.setObjectName("lineedit")
        self.label1b = QtGui.QLabel(Dialog)
        self.label1b.setGeometry(QtCore.QRect(290, 43, 121, 16))
        self.label1b.setObjectName("label1b")
        self.combobox1b = QtGui.QComboBox(Dialog)
        self.combobox1b.setGeometry(QtCore.QRect(380, 41, 51, 16))
        self.combobox1b.setObjectName("combobox1b")
        self.label1c = QtGui.QLabel(Dialog)
        self.label1c.setGeometry(QtCore.QRect(460, 43, 121, 16))
        self.label1c.setObjectName("label1c")
        self.combobox1c = QtGui.QComboBox(Dialog)
        self.combobox1c.setGeometry(QtCore.QRect(510, 41, 100, 16))
        self.combobox1c.setObjectName("combobox1c")
        self.label1d = QtGui.QLabel(Dialog)
        self.label1d.setGeometry(QtCore.QRect(640, 43, 121, 16))
        self.label1d.setObjectName("label1d")
        self.combobox1d = QtGui.QComboBox(Dialog)
        self.combobox1d.setGeometry(QtCore.QRect(690, 41, 100, 16))
        self.combobox1d.setObjectName("combobox1d")

        self.label2 = QtGui.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(20, 93, 121, 16))
        self.label2.setObjectName("label2")
        self.lineedit2 = QtGui.QLineEdit(Dialog)
        self.lineedit2.setGeometry(QtCore.QRect(95, 90, 42, 22))
        self.lineedit2.setFont(font)
        self.lineedit2.setObjectName("lineedit2")
        self.label2b = QtGui.QLabel(Dialog)
        self.label2b.setGeometry(QtCore.QRect(170, 93, 121, 16))
        self.label2b.setObjectName("label2b")
        self.combobox2b = QtGui.QComboBox(Dialog)
        self.combobox2b.setGeometry(QtCore.QRect(260, 91, 51, 16))
        self.combobox2b.setObjectName("combobox2b")
        self.label2c = QtGui.QLabel(Dialog)
        self.label2c.setGeometry(QtCore.QRect(340, 93, 121, 16))
        self.label2c.setObjectName("label2c")
        self.combobox2c = QtGui.QComboBox(Dialog)
        self.combobox2c.setGeometry(QtCore.QRect(390, 91, 100, 16))
        self.combobox2c.setObjectName("combobox2c")

        self.bouton3 = QtGui.QPushButton("Change Color", Dialog)
        self.bouton3.setGeometry(QtCore.QRect(165, 140, 91, 22))
        self.label3 = QtGui.QLabel(Dialog)
        self.label3.setGeometry(QtCore.QRect(20, 143, 121, 16))
        self.label3.setObjectName("label3")
        self.lineedit3 = QtGui.QLineEdit(Dialog)
        self.lineedit3.setGeometry(QtCore.QRect(105, 140, 22, 22))
        self.lineedit3.setFont(font)
        self.lineedit3.setObjectName("lineedit3")
        self.label3b = QtGui.QLabel(Dialog)
        self.label3b.setGeometry(QtCore.QRect(290, 143, 121, 16))
        self.label3b.setObjectName("label3b")
        self.combobox3b = QtGui.QComboBox(Dialog)
        self.combobox3b.setGeometry(QtCore.QRect(380, 141, 51, 16))
        self.combobox3b.setObjectName("combobox3b")
        self.label3c = QtGui.QLabel(Dialog)
        self.label3c.setGeometry(QtCore.QRect(460, 143, 121, 16))
        self.label3c.setObjectName("label3c")
        self.combobox3c = QtGui.QComboBox(Dialog)
        self.combobox3c.setGeometry(QtCore.QRect(510, 141, 100, 16))
        self.combobox3c.setObjectName("combobox3c")
        self.label3d = QtGui.QLabel(Dialog)
        self.label3d.setGeometry(QtCore.QRect(640, 143, 121, 16))
        self.label3d.setObjectName("label3d")
        self.combobox3d = QtGui.QComboBox(Dialog)
        self.combobox3d.setGeometry(QtCore.QRect(690, 141, 100, 16))
        self.combobox3d.setObjectName("combobox3d")

        self.label4 = QtGui.QLabel(Dialog)
        self.label4.setGeometry(QtCore.QRect(20, 193, 121, 16))
        self.label4.setObjectName("label4")
        self.lineedit4 = QtGui.QLineEdit(Dialog)
        self.lineedit4.setGeometry(QtCore.QRect(95, 190, 42, 22))
        self.lineedit4.setFont(font)
        self.lineedit4.setObjectName("lineedit4")
        self.label4b = QtGui.QLabel(Dialog)
        self.label4b.setGeometry(QtCore.QRect(170, 193, 121, 16))
        self.label4b.setObjectName("label4b")
        self.combobox4b = QtGui.QComboBox(Dialog)
        self.combobox4b.setGeometry(QtCore.QRect(260, 191, 51, 16))
        self.combobox4b.setObjectName("combobox4b")
        self.label4c = QtGui.QLabel(Dialog)
        self.label4c.setGeometry(QtCore.QRect(340, 193, 121, 16))
        self.label4c.setObjectName("label4c")
        self.combobox4c = QtGui.QComboBox(Dialog)
        self.combobox4c.setGeometry(QtCore.QRect(390, 191, 100, 16))
        self.combobox4c.setObjectName("combobox4c")
		
        self.label5 = QtGui.QLabel(Dialog)
        self.label5.setGeometry(QtCore.QRect(20, 243, 121, 16))
        self.label5.setObjectName("label5")
        self.combobox5 = QtGui.QComboBox(Dialog)
        self.combobox5.setGeometry(QtCore.QRect(95, 241, 51, 16))
        self.combobox5.setObjectName("combobox5")
        self.label5b = QtGui.QLabel(Dialog)
        self.label5b.setGeometry(QtCore.QRect(190, 243, 121, 16))
        self.label5b.setObjectName("label5b")
        self.combobox5b = QtGui.QComboBox(Dialog)
        self.combobox5b.setGeometry(QtCore.QRect(235, 241, 100, 16))
        self.combobox5b.setObjectName("combobox5b")
        self.label5c = QtGui.QLabel(Dialog)
        self.label5c.setGeometry(QtCore.QRect(380, 243, 121, 16))
        self.label5c.setObjectName("label5c")
        self.lineedit5c = QtGui.QLineEdit(Dialog)
        self.lineedit5c.setGeometry(QtCore.QRect(425, 240, 42, 22))
        self.lineedit5c.setFont(font)
        self.lineedit5c.setObjectName("lineedit5c")

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label1.setText(QtGui.QApplication.translate("Dialog", "<b>Node Color</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label1b.setText(QtGui.QApplication.translate("Dialog", "Proportional ?", None, QtGui.QApplication.UnicodeUTF8))
        self.label1c.setText(QtGui.QApplication.translate("Dialog", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.label1d.setText(QtGui.QApplication.translate("Dialog", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label2.setText(QtGui.QApplication.translate("Dialog", "<b>Node Size</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label2b.setText(QtGui.QApplication.translate("Dialog", "Proportional ?", None, QtGui.QApplication.UnicodeUTF8))
        self.label2c.setText(QtGui.QApplication.translate("Dialog", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.label3.setText(QtGui.QApplication.translate("Dialog", "<b>Edge Color</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label3b.setText(QtGui.QApplication.translate("Dialog", "Proportional ?", None, QtGui.QApplication.UnicodeUTF8))
        self.label3c.setText(QtGui.QApplication.translate("Dialog", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.label3d.setText(QtGui.QApplication.translate("Dialog", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label4.setText(QtGui.QApplication.translate("Dialog", "<b>Edge Size</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label4b.setText(QtGui.QApplication.translate("Dialog", "Proportional ?", None, QtGui.QApplication.UnicodeUTF8))
        self.label4c.setText(QtGui.QApplication.translate("Dialog", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.label5.setText(QtGui.QApplication.translate("Dialog", "<b>Label ?</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label5b.setText(QtGui.QApplication.translate("Dialog", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.label5c.setText(QtGui.QApplication.translate("Dialog", "Size", None, QtGui.QApplication.UnicodeUTF8))

